services:
  wgdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wgdashboard
    stdin_open: true
    tty: true
    ports:
      - "10086:10086"
      - "51820:51820/udp"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
